env:
  browser: true
# extends: 'eslint-config-es5'
parserOptions:
  ecmaVersion: 6
  sourceType: module
ecmaFeatures:
  modules: true
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  func-names: 0
#
# {
#     "parserOptions": {
#         "ecmaVersion": 6,
#         "sourceType": "module",
#         "ecmaFeatures": {
#             "jsx": true
#         }
#     },
#     "rules": {
#         "semi": 2
#     }
# }
